---
all:
  hosts:
    chippendale:
      ansible_port: 22
      ansible_host: 192.168.1.150
    bonham:
      ansible_port: 22
      ansible_host: 192.168.1.151
  vars:
    ansible_user: ollie

kubeMaster:
  hosts:
    chippendale:

kubeChildren:
  hosts:
    bonham:

NFSServer:
  hosts:
    chippendale:
  vars:
    diskUUID: 5B880AD3593B7D13

NFSChildren:
  hosts:
    bonham:

