---
all:
  hosts:
    chippendale:
      ansible_port: 22
      ansible_host: 192.168.1.150
    bonham:
      ansible_port: 22
      ansible_host: 192.168.1.151
    moon:
      ansible_port: 22
      ansible_host: 192.168.1.152
  vars:
    ansible_user: ollie

kubeMaster:
  hosts:
    chippendale:

kubeChildren:
  hosts:
    bonham:
    moon:

NFSServer:
  hosts:
    chippendale:
  vars:
    # The uuid of the usb disk/s to mount. Use blkid to find.
    diskUUID: 5B880AD3593B7D13

NFSChildren:
  hosts:
    bonham:
    moon:

